### ISSUE TITLE
Adaptar cociente de grupos tanto para 3.4 como para 2.7

### ISSUE THREAD

**Issue by pedritomelenas** [pedritomelenas/Algebra-II#1]
Por ahora el cociente de grupos está definido para 3.4 como G/H, con H subgrupo normal de G. Arreglar y hacerlo como en el original de Naftali

**Comment by pedritomelenas** [comment]
Hecho, basta con definir **div** también

**Comment by jlbueso** [comment]
A ver si te gustan así las tablas de grupos.
Además seguro que mejoras, lo que he escrito
Pepe

{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "from ipy_table import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<table border=\"1\" cellpadding=\"3\" cellspacing=\"0\"  style=\"border:1px solid black;border-collapse:collapse;\"><tr><td  style=\"background-color:White;border-left: 1px solid transparent;border-top: 1px solid transparent;\">$Z_3$</td><td  style=\"background-color:Red;\">1</td><td  style=\"background-color:Yellow;\">2</td><td  style=\"background-color:Lime;\">3</td></tr><tr><td  style=\"background-color:Red;\">1</td><td  style=\"background-color:Red;\">1</td><td  style=\"background-color:Yellow;\">2</td><td  style=\"background-color:Lime;\">3</td></tr><tr><td  style=\"background-color:Yellow;\">2</td><td  style=\"background-color:Yellow;\">2</td><td  style=\"background-color:Lime;\">3</td><td  style=\"background-color:Red;\">1</td></tr><tr><td  style=\"background-color:Lime;\">3</td><td  style=\"background-color:Lime;\">3</td><td  style=\"background-color:Red;\">1</td><td  style=\"background-color:Yellow;\">2</td></tr></table>"
      ],
      "text/plain": [
       "<ipy_table.IpyTable at 0x4606ba8>"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "html_colors = {0:'White',1:'Red', 2:'Yellow', 3:'Lime'}\n",
    "example_table = [[0,1,2,3],[1,1,2,3],[2,2,3,1],[3,3,1,2]]# Copy the example table\n",
    "make_table(example_table,interactive=False)\n",
    "for i in range(len(example_table)):\n",
    "    for j in range(len(example_table[i])):\n",
    "        set_cell_style(i, j,color=html_colors[example_table[i][j]])\n",
    "set_cell_style(0,0, no_border='left,top',color=html_colors[0])         \n",
    "example_table[0][0] = '$Z_3$'   # Clear the contents of the upper left corner cell\n",
    "render()      "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.4.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}

**Comment by pedritomelenas** [comment]
Ahora tengo que ver cómo integrarlo con el comando print...

**Comment by pedritomelenas** [comment]
lo muevo a otra conversación
