### ISSUE TITLE
Decidir cómo representar permutaciones

### ISSUE THREAD

**Issue by pedritomelenas** [pedritomelenas/Algebra-II#3]
Por ahora las permutaciones se definen por t-uplas, tal y como lo programó originalmente Naftali Harris.

**Comment by pedritomelenas** [comment]
Esto ya se ha cambiado en la nueva forma de definir permutaciones

**Comment by jlbueso** [comment]
Problemas con DihedralGroup en el caso "permutations" en python 3.4

c:/Users/pp-portatil/absalg-new\Group.py in DihedralGroup(n, rep) 673 if 
rep=="permutations":674 G=SymmetricGroup(n)--> 
675r=G(permutation(tuple([i+1 for i in range(n-1)]))) en python 2.7 
funciona bien. Saludos Pepe Bueso

**Comment by pedritomelenas** [comment]
vamos a abrir una nueva issue

**Comment by pedritomelenas** [comment]
El problema está en n/2; python 3.4 lo interpreta como un racional, arreglado
