### ISSUE TITLE
Acciones de grupos

### ISSUE THREAD

**Issue by pedritomelenas** [pedritomelenas/Algebra-II#6]
Implementar acciones de grupos

**Comment by jlbueso** [comment]
is_isomorphic da problemas en python 3.4

AttributeError                             Traceback (most recent call last)
<ipython-input-17-f42b82e9028d>  in<module>() ----> 
1G.is_isomorphic(CyclicGroup(5))c:/Users/pp/absalg-new\Group.py in 
is_isomorphic(self, other) 490 def is_isomorphic(self, other):491 
"""Checks if self and other are isomorphic"""--> 492return 
bool(self.find_isomorphism(other))493 494 def intersection(self, 
other):c:/Users/pp/absalg-new\Group.py in find_isomorphism(self, other) 
457 for B in itertools.permutations(other, len(A)):458 --> 459func = 
dict(itertools.izip(A, B)) # the mapping460 counterexample = False461 
while not counterexample:AttributeError: 'module' object has no 
attribute 'izip'

**Comment by pedritomelenas** [comment]
Lo miro, en python 3 izip es global, no cuelga de itertools...

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 31 de octubre de 2015 9:51:29 p. m. jlbueso notifications@github.com 
escribio:

**Comment by pedritomelenas** [comment]
Hecho... Ya está solucionado.
Es mejor abrir una nueva "issue" para esto.

**Comment by pedritomelenas** [comment]
Ya está incluido

**Comment by jlbueso** [comment]
Una pregunta sobre acciones
Como introduzco la acción de conjugación.
En este caso el conjunto X es el propio G  y la acción es  x_y_x**-1

Convendría tener una función conjugate
conjugate(G,x,y) diese x_y_x**-1 en G

Saludos
Pepe Bueso

**Comment by jlbueso** [comment]
He definido conjugate y la acción de conjugación. Asímismo el 
centralizador que no estaba hecho. He comprobado que para la acción de 
conjugación sale la clase de conjugación y el centralizador.
Mañana te lo enseño. para que lo repases.
Saludos
Pepe Bueso

**Comment by pedritomelenas** [comment]
Un ejemplo de lo que pides con acciones

```
In [29]: G=SymmetricGroup(3)

In [30]: X=G.Set

In [31]: f=GroupAction(G,X,lambda g,x:(g*G(x)*g**-1).elem)

In [32]: p=permutation(2,3,1)

In [34]: f.orbit(p)
Out[34]: frozenset({ (1, 2, 3),  (1, 3, 2)})

In [42]: G(p).conjugacy_class()
Out[42]: frozenset({ (1, 2, 3),  (1, 3, 2)})
```

Y con el centralizador:

```
In [44]: list(G(p).centralizer())
Out[44]: [( ),  (1, 2, 3),  (1, 3, 2)]

In [45]: list(f.stabilizer(p))
Out[45]: [( ),  (1, 2, 3),  (1, 3, 2)]
```

¿Es esto lo que buscas?
Gracias

**Comment by jlbueso** [comment]
Perdona la confusión, no veia implementado entralizer.

**Comment by pedritomelenas** [comment]
Yo tampoco me acordaba! Lo añadiré al tutorial.
Gracias

Enviado con Aquamail para Android
http://www.aqua-mail.com

El 23 de noviembre de 2015 4:55:06 p. m. jlbueso notifications@github.com 
escribio:
