### ISSUE TITLE
preguntas

### ISSUE THREAD

**Issue by jlbueso** [pedritomelenas/Algebra-II#8]
is_element(p.G)
is_subgroup(L,G) donde L es una lista,tupla, conjunto
is_simple(G)

**Comment by pedritomelenas** [comment]
- is_element(p,G) se puede hacer con g in G.Set
- is_sugroup está implementado como G.subgroup_by_elems(ls) con ls una lista de G.Set o de G. Comprueba si es cerrada para la operación de grupo, y de ser así devuelve el subgrupo de G cuyos elementos son los elements de ls.
- is_simple(G) se comprueba ahora con G.is_simple()
